[project]
name = "rl-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gym>=0.26.2",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "torch>=2.7.0",
]
